version: "3.4"

services:
  frontend:
    image: client
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
      - 24678:24678
    volumes:
      - ./:/usr/src/prod/app
      #- ../../core/output
      - /usr/src/prod/app/node_modules
   # networks:
   #   - proxy
 # nginx:
 #   build: 
 #     context: .
  #    dockerfile: /nginx/Dockerfile
  #  container_name: "client_nginx"
  #  volumes:
  #    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  #  depends_on:
  #    - client
  #  ports:
  #    - 4001:4001  
    networks:
      - proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.fr-secure.entrypoints=websecure"
      - "traefik.http.routers.fr-secure.rule=Host(`devop.findcar.parts`)" 
      - "traefik.http.routers.fr-secure.tls.certresolver=letsencrypt"
      #- "traefik.http.routers.fr-secure.service=api@external"
      - 'traefik.http.routers.fr-secure.middlewares=strip'
      - 'traefik.http.middlewares.strip.stripprefix.prefixes=/traefik'
      
networks:
  proxy:
    external: true      